### ISSUE TITLE
add support for addresses

### ISSUE THREAD

**Issue by bb-git** [mostachoio/MoABContactsManager#1]
Hi,
I like using the ContactsManager as it is really fast. But I would also need the addresses of the contacts, is it possible to add this feature?

Thanks

**Comment by diegof29** [comment]
Hi,
Thanks for using the lib, I'm glad you like it.
Sure I can add it. I'm on it :)

**Comment by bb-git** [comment]
Great, works like a charm :)
Is there a possibility to access the contactId in the completion callback after creating a contact?
what happens if I update a contact, that doesn't exist any more?

**Comment by diegof29** [comment]
Nothing will happens if you update a contact that doesn't exist (it won't create a new contact)

**Comment by bb-git** [comment]
Awesome :)
